# Generated by Django 3.1.7 on 2021-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='answer1',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='answer2',
            new_name='op1',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='op2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='op3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='op4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
