# Generated by Django 3.1.7 on 2021-07-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210728_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionModel',
            new_name='QuesModel',
        ),
    ]
